import type { Product } from "./CartContext";

export const CATEGORIES = [
  "All Products",
  "Sweets",
  "Snacks",
  "Healthy Snacks",
  "Podis",
  "Oils & Ghee",
  "Veg Pickles",
  "Non-Veg Pickles",
  "Gift Boxes",
];

export const PRODUCTS: Product[] = [
  // ---- Sweets
  { id: "p1", name: "Kova", price: 0, weight: "250g", category: "Sweets", image: "/images/Kova.jpg" },
  { id: "p2", name: "Bellam Laddu (Nuvvu/Rava type)", price: 0, weight: "250g", category: "Sweets", image: "/images/Bellam Laddu (Nuvvu-Rava type).jpg" },
  { id: "p3", name: "Dry Kajjikayalu", price: 0, weight: "250g", category: "Sweets", image: "/images/Dry Kajjikayalu.jpg" },
  { id: "p4", name: "Rava Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Rava Laddu.jpg" },
  { id: "p5", name: "Minapa Sunnundalu", price: 0, weight: "250g", category: "Sweets", image: "/images/Minapa Sunnundalu.jpg" },
  { id: "p6", name: "Kakinada Kaja (Madatha)", price: 0, weight: "250g", category: "Sweets", image: "/images/Kakinada Kaja (Madatha).jpg" },
  { id: "p7", name: "Pootharekulu", price: 0, weight: "250g", category: "Sweets", image: "/images/Pootharekulu.jpg" },
  { id: "p8", name: "Arisallu / Nuvvula Arisallu", price: 0, weight: "250g", category: "Sweets", image: "/images/Arisallu - Nuvvula Arisallu.jpg" },
  { id: "p9", name: "Boondi Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Boondi Laddu.jpg" },
  { id: "p10", name: "Thakudhu Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Thakudhu Laddu.jpg" },
  { id: "p11", name: "Kobbari Undha (Laddu)", price: 0, weight: "250g", category: "Sweets", image: "/images/Kobbari Undha (Laddu).jpg" },
  { id: "p12", name: "Pootharekulu (Palm sugar type)", price: 0, weight: "250g", category: "Sweets", image: "/images/Pootharekulu (Palm sugar type).jpg" },
  { id: "p13", name: "Kobbari Arisallu", price: 0, weight: "250g", category: "Sweets", image: "/images/Kobbari Arisallu.jpg" },
  { id: "p14", name: "Dry Fruit Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Dry Fruit Laddu.jpg" },
  { id: "p15", name: "Halwa", price: 0, weight: "250g", category: "Sweets", image: "/images/Halwa.jpg" },
  { id: "p16", name: "Bellam Gavvalu", price: 0, weight: "250g", category: "Sweets", image: "/images/Bellam Gavvalu.jpg" },
  { id: "p17", name: "Bellam Kommulu", price: 0, weight: "250g", category: "Sweets", image: "/images/Bellam Kommulu.jpg" },
  { id: "p18", name: "Ragi Bellam Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Ragi Bellam Laddu.jpg" },
  { id: "p19", name: "Nuvvula Laddu", price: 0, weight: "250g", category: "Sweets", image: "/images/Nuvvula Laddu.jpg" },
  { id: "p20", name: "Panirulu", price: 0, weight: "250g", category: "Sweets", image: "/images/Panirulu.jpg" },
  { id: "p21", name: "Gormithilu", price: 0, weight: "250g", category: "Sweets", image: "/images/Gormithilu.jpg" },
  { id: "p22", name: "Pongadalu", price: 0, weight: "250g", category: "Sweets", image: "/images/Pongadalu.jpg" },
  { id: "p23", name: "Chalimidi", price: 0, weight: "250g", category: "Sweets", image: "/images/Chalimidi.jpg" },

  // ---- Snacks
  { id: "p24", name: "Chekkalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Chekkalu.jpg" },
  { id: "p25", name: "Murukulu", price: 0, weight: "250g", category: "Snacks", image: "/images/Murukulu.jpg" },
  { id: "p26", name: "Chekodhi", price: 0, weight: "250g", category: "Snacks", image: "/images/Chekodhi.jpg" },
  { id: "p27", name: "Ribbon Pakodi (Akku Pakodi)", price: 0, weight: "250g", category: "Snacks", image: "/images/Ribbon Pakodi (Akku Pakodi).jpg" },
  { id: "p28", name: "Karam Boondi", price: 0, weight: "250g", category: "Snacks", image: "/images/Karam Boondi.jpg" },
  { id: "p29", name: "Ganapathi Special Mixture", price: 0, weight: "250g", category: "Snacks", image: "/images/Ganapathi Special Mixture.jpg" },
  { id: "p30", name: "Karam Jantikalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Karam Jantikalu.jpg" },
  { id: "p31", name: "Kommulu", price: 0, weight: "250g", category: "Snacks", image: "/images/Kommulu.jpg" },
  { id: "p32", name: "Garlic Murukulu (Vammu Pusa)", price: 0, weight: "250g", category: "Snacks", image: "/images/Garlic Murukulu (Vammu Pusa).jpg" },
  { id: "p33", name: "Masala Pusa", price: 0, weight: "250g", category: "Snacks", image: "/images/Masala Pusa.jpg" },
  { id: "p34", name: "Special Mixture", price: 0, weight: "250g", category: "Snacks", image: "/images/Special Mixture.jpg" },
  { id: "p35", name: "Chitti Appadalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Chitti Appadalu.jpg" },
  { id: "p36", name: "Nagaram Gavvalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Nagaram Gavvalu.jpg" },
  { id: "p37", name: "Nylaram Chekkalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Nylaram Chekkalu.jpg" },
  { id: "p38", name: "Mamidi Thondri", price: 0, weight: "250g", category: "Snacks", image: "/images/Mamidi Thondri.jpg" },
  { id: "p39", name: "Thati Chapa", price: 0, weight: "250g", category: "Snacks", image: "/images/Thati Chapa.jpg" },
  { id: "p40", name: "Bellam Jeedilu", price: 0, weight: "250g", category: "Snacks", image: "/images/Bellam Jeedilu.jpg" },
  { id: "p41", name: "Nuvvula Jeedilu", price: 0, weight: "250g", category: "Snacks", image: "/images/Nuvvula Jeedilu.jpg" },
  { id: "p42", name: "Chinna Boondi Aachu", price: 0, weight: "250g", category: "Snacks", image: "/images/Chinna Boondi Aachu.jpg" },
  { id: "p43", name: "Jeedi Pappu Aachu", price: 0, weight: "250g", category: "Snacks", image: "/images/Jeedi Pappu Aachu.jpg" },
  { id: "p44", name: "Pallila Aachu", price: 0, weight: "250g", category: "Snacks", image: "/images/Pallila Aachu.jpg" },
  { id: "p45", name: "Masala Cashew", price: 0, weight: "200g", category: "Snacks", image: "/images/Masala Cashew.jpg" },
  { id: "p46", name: "Pepper Cashew", price: 0, weight: "200g", category: "Snacks", image: "/images/Pepper Cashew.jpg" },
  { id: "p47", name: "Masala Batani (Kabuli Chana)", price: 0, weight: "250g", category: "Snacks", image: "/images/Masala Batani (Kabuli Chana).jpg" },
  { id: "p48", name: "Onion Chekodhi", price: 0, weight: "250g", category: "Snacks", image: "/images/Onion Chekodhi.jpg" },
  { id: "p49", name: "Gulabi Jantikalu", price: 0, weight: "250g", category: "Snacks", image: "/images/Gulabi Jantikalu.jpg" },
  { id: "p50", name: "Ringulu", price: 0, weight: "250g", category: "Snacks", image: "/images/Ringulu.jpg" },

  // ---- Healthy Snacks
  { id: "p51", name: "Ragi Ringulu", price: 0, weight: "250g", category: "Healthy Snacks", image: "/images/Ragi Ringulu.jpg" },
  { id: "p52", name: "Ragi Jantikalu", price: 0, weight: "250g", category: "Healthy Snacks", image: "/images/Ragi Jantikalu.jpg" },
  { id: "p53", name: "Ragi Chekkalu", price: 0, weight: "250g", category: "Healthy Snacks", image: "/images/Ragi Chekkalu.jpg" },
  { id: "p54", name: "Beetroot Jantikalu", price: 0, weight: "250g", category: "Healthy Snacks", image: "/images/Beetroot Jantikalu.jpg" },
  { id: "p55", name: "Beetroot Chekkalu", price: 0, weight: "250g", category: "Healthy Snacks", image: "/images/Beetroot Chekkalu.jpg" },

  // ---- Podis
  { id: "p56", name: "Karvepaku Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Karvepaku Podi.jpg" },
  { id: "p57", name: "Mulaga Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Mulaga Podi.jpg" },
  { id: "p58", name: "Karam Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Karam Podi.jpg" },
  { id: "p59", name: "Velluli Karvepaku Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Velluli Karvepaku Podi.jpg" },
  { id: "p60", name: "Sonti Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Sonti Podi.jpg" },
  { id: "p61", name: "Kandi Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Kandi Podi.jpg" },
  { id: "p62", name: "Usiri Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Usiri Podi.jpg" },
  { id: "p63", name: "Nuvvula Karam Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Nuvvula Karam Podi.jpg" },
  { id: "p64", name: "Daniyalu Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Daniyalu Podi.jpg" },
  { id: "p65", name: "Tilakota Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Tilakota Podi.jpg" },
  { id: "p66", name: "Avise Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Avise Podi.jpg" },
  { id: "p67", name: "Kakara Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Kakara Podi.jpg" },
  { id: "p68", name: "Nuvvula Podi (Telaga Pindi)", price: 0, weight: "200g", category: "Podis", image: "/images/Nuvvula Podi (Telaga Pindi).jpg" },
  { id: "p69", name: "Miriyala Podi", price: 0, weight: "200g", category: "Podis", image: "/images/Miriyala Podi.jpg" },

  // ---- Oils & Ghee
  { id: "p70", name: "Nuvvula Nune", price: 0, weight: "1L", category: "Oils & Ghee", image: "/images/Nuvvula Nune.jpg" },
  { id: "p71", name: "Kobbari Nune", price: 0, weight: "1L", category: "Oils & Ghee", image: "/images/Kobbari Nune.jpg" },
  { id: "p72", name: "Groundnut Oil", price: 0, weight: "1L", category: "Oils & Ghee", image: "/images/Groundnut Oil.jpg" },
  { id: "p73", name: "Ghee (Cow)", price: 0, weight: "500ml", category: "Oils & Ghee", image: "/images/Ghee (Cow).jpg" },
  { id: "p74", name: "Ghee (Buffalo)", price: 0, weight: "500ml", category: "Oils & Ghee", image: "/images/Ghee (Buffalo).jpg" },

  // ---- Veg Pickles
  { id: "p75", name: "Gongura", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Gongura.jpg" },
  { id: "p76", name: "Avakaya", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Avakaya.jpg" },
  { id: "p77", name: "Mixed Pickle", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Mixed Pickle.jpg" },
  { id: "p78", name: "Magaya", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Magaya.jpg" },
  { id: "p79", name: "Allam Pickle", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Allam Pickle.jpg" },
  { id: "p80", name: "Tomato Pickle", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Tomato Pickle.jpg" },
  { id: "p81", name: "Usirikaya Pickle", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Usirikaya Pickle.jpg" },
  { id: "p82", name: "Chinthakaya Pickle", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Chinthakaya Pickle.jpg" },
  { id: "p83", name: "Cauliflower", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Cauliflower.jpg" },
  { id: "p84", name: "Lemon", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Lemon.jpg" },
  { id: "p85", name: "Kothimeera", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Kothimeera.jpg" },
  { id: "p86", name: "Karvepaku", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Karvepaku.jpg" },
  { id: "p87", name: "Dosakaya", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Dosakaya.jpg" },
  { id: "p88", name: "Mulakkaya Pachadi", price: 0, weight: "250g", category: "Veg Pickles", image: "/images/Mulakkaya Pachadi.jpg" },

  // ---- Non-Veg Pickles
  { id: "p89", name: "Chicken Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Chicken Pickle.jpg" },
  { id: "p90", name: "Gongura Chicken Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Gongura Chicken Pickle.jpg" },
  { id: "p91", name: "Mutton Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Mutton Pickle.jpg" },
  { id: "p92", name: "Gongura Mutton Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Gongura Mutton Pickle.jpg" },
  { id: "p93", name: "Prawns Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Prawns Pickle.jpg" },
  { id: "p94", name: "Gongura Prawns Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Gongura Prawns Pickle.jpg" },
  { id: "p95", name: "Crab Pickle", price: 0, weight: "250g", category: "Non-Veg Pickles", image: "/images/Crab Pickle.jpg" },

  // ---- Gift Boxes
  { id: "p96", name: "Sweet Combo Box (Small)", price: 0, weight: "Assorted", category: "Gift Boxes", image: "/images/Sweet Combo Box (Small).jpg" },
  { id: "p97", name: "Sweet Combo Box (Medium)", price: 0, weight: "Assorted", category: "Gift Boxes", image: "/images/Sweet Combo Box (Medium).jpg" },
  { id: "p98", name: "Festive Gift Hamper", price: 0, weight: "Assorted", category: "Gift Boxes", image: "/images/Festive Gift Hamper.jpg" },
];
