// app/components/data.ts
import type { Product } from "./CartContext";
import { PRICE_BY_ID, type PackSize } from "./prices";

export type ProductData = Product & {
  highlights: string[];
};

export const CATEGORIES = [
  "All Products",
  "Sweets",
  "Snacks",
  "Healthy Snacks",
  "Podis",
  "Oils & Ghee",
  "Veg Pickles",
  "Non-Veg Pickles",
  "Gift Boxes",
];

function priceFor(id: string, weight: string): number {
  const table = PRICE_BY_ID[id];
  if (!table) return 0;

  // weight in your data is like "250g", "200g", "1L", "500ml", "Assorted"
  const key = weight as PackSize;
  return table[key] ?? 0;
}

export const PRODUCTS: ProductData[] = [

  // ---- Sweets
  {
    id: "p1",
    name: "Kova",
    weight: "250g",
    category: "Sweets",
    image: "/images/Kova.jpg",
    price: priceFor("p1", "250g"),
    highlights: [
      "Rich, slow-cooked milk sweet with a soft texture",
      "Made in small batches for freshness",
      "Perfect for festivals and gifting",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p2",
    name: "Bellam Laddu (Nuvvu/Rava type)",
    weight: "250g",
    category: "Sweets",
    image: "/images/Bellam Laddu (Nuvvu-Rava type).jpg",
    price: priceFor("p2", "250g"),
    highlights: [
      "Traditional jaggery laddu with nuvvu/rava blend",
      "Natural sweetness with an authentic homemade taste",
      "Energy-rich festive sweet",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p3",
    name: "Dry Kajjikayalu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Dry Kajjikayalu.jpg",
    price: priceFor("p3", "250g"),
    highlights: [
      "Crispy sweet pockets with traditional stuffing",
      "Lightly fried for crunch and aroma",
      "Great tea-time sweet snack",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p4",
    name: "Rava Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Rava Laddu.jpg",
    price: priceFor("p4", "250g"),
    highlights: [
      "Classic rava laddu with ghee-rich flavor",
      "Soft bite with roasted aroma",
      "Perfect for pooja and festive sharing",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p5",
    name: "Minapa Sunnundalu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Minapa Sunnundalu.jpg",
    price: priceFor("p5", "250g"),
    highlights: [
      "Protein-rich urad dal laddus (Andhra special)",
      "Roasted minapa for deep nutty flavor",
      "Traditionally made for Sankranti & festivals",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p6",
    name: "Kakinada Kaja (Madatha)",
    weight: "250g",
    category: "Sweets",
    image: "/images/Kakinada Kaja (Madatha).jpg",
    price: priceFor("p6", "250g"),
    highlights: [
      "Iconic Kakinada-style layered kaja",
      "Crispy outside with syrupy sweetness",
      "Authentic texture and crunch",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p7",
    name: "Pootharekulu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Pootharekulu.jpg",
    price: priceFor("p7", "250g"),
    highlights: [
      "Paper-thin sweet rolls (Godavari specialty)",
      "Jaggery/ghee filling with delicate layers",
      "Light, melt-in-mouth festival sweet",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p8",
    name: "Arisallu / Nuvvula Arisallu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Arisallu - Nuvvula Arisallu.jpg",
    price: priceFor("p8", "250g"),
    highlights: [
      "Traditional ariselu made with rice & jaggery",
      "Nuvvula variant adds roasted sesame aroma",
      "Festive sweet for Sankranti celebrations",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p9",
    name: "Boondi Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Boondi Laddu.jpg",
    price: priceFor("p9", "250g"),
    highlights: [
      "Soft laddus made from fine boondi pearls",
      "Ghee-forward taste with festive feel",
      "Perfect for gifting and celebrations",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p10",
    name: "Thakudhu Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Thakudhu Laddu.jpg",
    price: priceFor("p10", "250g"),
    highlights: [
      "Traditional laddu variety with authentic taste",
      "Prepared in small batches for freshness",
      "Rich, sweet bite ideal for festivals",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p11",
    name: "Kobbari Undha (Laddu)",
    weight: "250g",
    category: "Sweets",
    image: "/images/Kobbari Undha (Laddu).jpg",
    price: priceFor("p11", "250g"),
    highlights: [
      "Coconut laddu made with fresh kobbari",
      "Sweet, aromatic and satisfying texture",
      "Great for pooja and gifting",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p12",
    name: "Pootharekulu (Palm sugar type)",
    weight: "250g",
    category: "Sweets",
    image: "/images/Pootharekulu (Palm sugar type).jpg",
    price: priceFor("p12", "250g"),
    highlights: [
      "Pootharekulu made with palm sugar sweetness",
      "Delicate paper layers with rich filling",
      "Traditional Godavari-style festival sweet",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p13",
    name: "Kobbari Arisallu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Kobbari Arisallu.jpg",
    price: priceFor("p13", "250g"),
    highlights: [
      "Ariselu with coconut flavor (kobbari twist)",
      "Rice & jaggery base with festive aroma",
      "Handmade in small batches",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p14",
    name: "Dry Fruit Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Dry Fruit Laddu.jpg",
    price: priceFor("p14", "250g"),
    highlights: [
      "Premium dry fruits and nuts in every bite",
      "Naturally rich and energy-dense sweet",
      "Ideal for gifting and healthy indulgence",
      "Best before: 20–30 days (airtight packed)",
    ],
  },
  {
    id: "p15",
    name: "Halwa",
    weight: "250g",
    category: "Sweets",
    image: "/images/Halwa.jpg",
    price: priceFor("p15", "250g"),
    highlights: [
      "Classic halwa with smooth, rich texture",
      "Slow-cooked for deep flavor",
      "Perfect dessert after meals",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p16",
    name: "Bellam Gavvalu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Bellam Gavvalu.jpg",
    price: priceFor("p16", "250g"),
    highlights: [
      "Crispy gavvalu coated in jaggery (bellam)",
      "Traditional snack-sweet with crunchy bite",
      "Festival favorite in Andhra homes",
      "Best before: 15–30 days (airtight packed)",
    ],
  },
  {
    id: "p17",
    name: "Bellam Kommulu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Bellam Kommulu.jpg",
    price: priceFor("p17", "250g"),
    highlights: [
      "Crunchy bellam kommulu with jaggery sweetness",
      "Traditional bite-size sweet snack",
      "Great for tea-time and gifting",
      "Best before: 15–30 days (airtight packed)",
    ],
  },
  {
    id: "p18",
    name: "Ragi Bellam Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Ragi Bellam Laddu.jpg",
    price: priceFor("p18", "250g"),
    highlights: [
      "Ragi-based laddu sweetened with jaggery",
      "Wholesome and energy-rich",
      "Traditional healthy sweet option",
      "Best before: 15–30 days (airtight packed)",
    ],
  },
  {
    id: "p19",
    name: "Nuvvula Laddu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Nuvvula Laddu.jpg",
    price: priceFor("p19", "250g"),
    highlights: [
      "Sesame laddu with roasted nuvvu aroma",
      "Jaggery sweetness with crunchy texture",
      "Great for winter and festivals",
      "Best before: 15–30 days (airtight packed)",
    ],
  },
  {
    id: "p20",
    name: "Panirulu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Panirulu.jpg",
    price: priceFor("p20", "250g"),
    highlights: [
      "Traditional sweet bites made for festive occasions",
      "Soft inside with a rich sweet flavor",
      "Made fresh in small batches",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p21",
    name: "Gormithilu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Gormithilu.jpg",
    price: priceFor("p21", "250g"),
    highlights: [
      "Traditional sweet snack with crunchy texture",
      "Made using authentic Andhra recipe",
      "Perfect for sharing during festivals",
      "Best before: 15–30 days (airtight packed)",
    ],
  },
  {
    id: "p22",
    name: "Pongadalu",
    weight: "250g",
    category: "Sweets",
    image: "/images/Pongadalu.jpg",
    price: priceFor("p22", "250g"),
    highlights: [
      "Traditional sweet snack with homestyle taste",
      "Prepared fresh and packed hygienically",
      "Great for festivals and gifting",
      "Best before: 10–15 days (airtight packed)",
    ],
  },
  {
    id: "p23",
    name: "Chalimidi",
    weight: "250g",
    category: "Sweets",
    image: "/images/Chalimidi.jpg",
    price: priceFor("p23", "250g"),
    highlights: [
      "Andhra festive sweet made with rice flour & jaggery",
      "Mild ghee aroma with soft, rich texture",
      "Commonly prepared for Sankranti & poojas",
      "Best before: 10–15 days (airtight packed)",
    ],
  },

  // ---- Snacks
  {
    id: "p24",
    name: "Chekkalu",
    weight: "250g",
    category: "Snacks",
    image: "/images/Chekkalu.jpg",
    price: priceFor("p24", "250g"),
    highlights: [
      "Crispy rice-flour snack with traditional spices",
      "Perfect with tea/coffee",
      "Made fresh for crunch",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p25",
    name: "Murukulu",
    weight: "250g",
    category: "Snacks",
    image: "/images/Murukulu.jpg",
    price: priceFor("p25", "250g"),
    highlights: [
      "Classic spiral snack with crunchy bite",
      "Lightly spiced and freshly fried",
      "Perfect for evening munching",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p26",
    name: "Chekodhi",
    weight: "250g",
    category: "Snacks",
    image: "/images/Chekodhi.jpg",
    price: priceFor("p26", "250g"),
    highlights: [
      "Crispy chekodhi with authentic masala flavor",
      "Ideal for tea-time snacking",
      "Fresh batch prepared for crunch",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p27",
    name: "Ribbon Pakodi (Akku Pakodi)",
    weight: "250g",
    category: "Snacks",
    image: "/images/Ribbon Pakodi (Akku Pakodi).jpg",
    price: priceFor("p27", "250g"),
    highlights: [
      "Ribbon-shaped crunchy snack with spice blend",
      "Crisp texture and homestyle taste",
      "Great for parties and tea-time",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p28",
    name: "Karam Boondi",
    weight: "250g",
    category: "Snacks",
    image: "/images/Karam Boondi.jpg",
    price: priceFor("p28", "250g"),
    highlights: [
      "Spicy boondi pearls with bold karam flavor",
      "Perfect for mixture and snacking",
      "Freshly made for crunch",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p29",
    name: "Ganapathi Special Mixture",
    weight: "250g",
    category: "Snacks",
    image: "/images/Ganapathi Special Mixture.jpg",
    price: priceFor("p29", "250g"),
    highlights: [
      "Signature mixture with crunchy components",
      "Balanced spice and flavor",
      "Best with tea and evening snacks",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p30",
    name: "Karam Jantikalu",
    weight: "250g",
    category: "Snacks",
    image: "/images/Karam Jantikalu.jpg",
    price: priceFor("p30", "250g"),
    highlights: [
      "Spicy jantikalu with crisp bite",
      "Traditional Andhra snack",
      "Freshly fried and packed",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p31",
    name: "Kommulu",
    weight: "250g",
    category: "Snacks",
    image: "/images/Kommulu.jpg",
    price: priceFor("p31", "250g"),
    highlights: [
      "Crunchy kommulu with traditional seasoning",
      "Perfect for tea-time munching",
      "Fresh batch prepared for crunch",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p32",
    name: "Garlic Murukulu (Vammu Pusa)",
    weight: "250g",
    category: "Snacks",
    image: "/images/Garlic Murukulu (Vammu Pusa).jpg",
    price: priceFor("p32", "250g"),
    highlights: [
      "Garlic-forward murukulu with bold flavor",
      "Crispy texture with vammu aroma",
      "Perfect with tea/coffee",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p33",
    name: "Masala Pusa",
    weight: "250g",
    category: "Snacks",
    image: "/images/Masala Pusa.jpg",
    price: priceFor("p33", "250g"),
    highlights: [
      "Crispy pusa snack with masala blend",
      "Light and crunchy bite",
      "Great for evening snack cravings",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p34",
    name: "Special Mixture",
    weight: "250g",
    category: "Snacks",
    image: "/images/Special Mixture.jpg",
    price: priceFor("p34", "250g"),
    highlights: [
      "Classic mixture with crunchy variety",
      "Balanced spice and taste",
      "Perfect for tea-time and guests",
      "Best before: 30–45 days (airtight packed)",
    ],
  },
  {
    id: "p35",
    name: "Chitti Appadalu",
    weight: "250g",
    category: "Snacks",
    image: "/images/Chitti Appadalu.jpg",
    price: priceFor("p35", "250g"),
    highlights: [
      "Mini appadalu with crisp bite",
      "Lightly spiced traditional snack",
      "Perfect for munching anytime",
      "Best before: 30–45 days (airtight packed)",
    ],
  },

  // (Keep your remaining products the same pattern...)
  // IMPORTANT: Continue using: price: priceFor("<id>", "<weight>")
];
